name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Instalar dependências
        run: npm install
      - name: Rodar testes
        run: npm test
      - name: Build
        run: npm run build

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Instalar dependências
        run: npm install
      - name: Rodar testes
        run: npm test
      - name: Build
        run: npm run build
